### PR TITLE
Add Menu Entry to HMI display "My Program"

### PR DESCRIPTION
**Pull request by sumedhreddy90**
## Description - Feature request

Summary:

This PR enables the users to launch their turtlebot4 application from HMI display by pressing "My Program" menu entry similar to that of EStop. Here, once the user clicks the button, `my_program` service request is requested to the server with a bool msg `my_program_on == True`. 
This boolean can be used as a Flag by the users in their turtlebot4 applications to create their own `my_program` server.
 For example,
```
 self.my_program_request = self.create_service(MyProgram, 'my_program', self.project_manager_callback)

def project_manager_callback(self, request, response):
        
        self.response_message = response.message
        self.response_result = response.success
        # If the client requests the service with my_program_on = True, we run a bash script of launch
        # Then return Success message upon successful request exectution
        if(request.my_program_on):
          # User business logic
        else:
            self.get_logger().info('My Program Mode rejected')
            response.message = "My Program Mode rejected and failed to run projects"
            response.success = False

        return response
```

## Type of change

- [ Menu Entry to HMI display] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

This feature is tested by creating a sample project. By pressing the `My Program` button on the HMI display, it enables us to run  a motion planner algorithm- this project is available on [Github repo](https://github.com/turtlebot/TurtleBot4Lessons/tree/main/projects/unit02_simulation_motion_planner)

Usage:

1. Create a new workspace and clone the below repo into src
```
mkdir tb4_ws
cd tb4_ws
mkdir src
cd tb4_ws/src
git clone https://github.com/turtlebot/TurtleBot4Lessons.git
colcon build
```
2. Launch TB4 ignition bring up using  hmi_simulation_project_manager
```
ros2 launch hmi_simulation_project_manager tb4_ignition.launch.py

```
3. Run hmi_simulation_project_manager manager.py script before pressing the button on the turtlebot4 display. This run file initiates all the required nodes for running motion planner algorithm.
```
ros2 run hmi_simulation_project_manager manager
```

## Checklist

- [x] I have performed a self-review of my own code and is under review by @kscottz 
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by sumedhreddy90** [comment]
Adding more slots to HMI display as discussed with @kscottz 

- [x] Added a total of 4 "My Program" slots for users to launch their programs from HMI display
- [x] First two slots are based on services  (My Program and My Program 1)
```
/my_program
/my_program_1
```
- [x] The next two slots are based on Action-Server (My Program 2 and My Program 3)
```
sumedh@starfleeet:~/workspace$ ros2 action list
```
```
/my_program_2
/my_program_3
```
Example:

Action-Client: 
```
[turtlebot4_node-32] [INFO] [1660626217.475454352] [turtlebot4_node]: My Program 2 Action-Server
[turtlebot4_node-32] [INFO] [1660626217.475498460] [turtlebot4_node]: Waiting for my_program_2 action server
[turtlebot4_node-32] [INFO] [1660626218.475679068] [turtlebot4_node]: my_program_2 action server available, sending goal
[turtlebot4_node-32] [INFO] [1660626218.476384658] [turtlebot4_node]: my_program_2 goal accepted by server, waiting for result
[turtlebot4_node-32] [INFO] [1660626218.486139249] [turtlebot4_node]: my_program_2 goal succeeded
```
Action-Server:
```
[INFO] [1660626218.485144909] [my_program_service]: Executing goal...
[INFO] [1660626218.485543875] [my_program_service]: Successfully Executed goal!
```

**Comment by roni-kreinin** [comment]
Can we rename the service to "UserService" and the action to "UserAction"? Also both services/actions should use the same .srv and .action. We do not need to duplicate them.

**Comment by sumedhreddy90** [comment]
@roni-kreinin renamed service to "UserService" and the action to "UserAction" and modified the code without duplications

**Comment by roni-kreinin** [comment]
Let's switch everything to a "User Service" or "User Action" naming convention. I think "MyProgram" is a bit too generic.

We can define UserAction.action as:
```
# Request
bool user_action_request
---
# Result
bool user_action_result
---
# Feedback
bool user_action_feedback
```

And then name the action clients as `user_action_1` and `user_action_2`. Similarly the actions themselves would be `/user_action_1` and `/user_action_2`.

We can do the same thing for services and call them `user_service_1` and `user_service_2`.

**Review by kscottz — CHANGES_REQUESTED** [review]
Unfortunately this still isn't quite right and I think we're overcomplicating what we really want to do. Our goal was to keep the interface on the Turtlebot as small as possible and do all of the heavy lifting in the lessons repository. To do this I propose that we use a dead simple message on the Turtlebot4 node, simply a single message with four bools that tracks when one of the menu entry is pressed. All the state management and heavy lifting should be done in the lessons repo so students are simply working on the messages and not modifying the TurtleBot4 package.  

Roughly it would look like:

TurtleBot4 ---> StudentProgramSlot Message ---> Lesson Manager --> Student Programs (triggered via a flag, service, or action)

This approach reduces the number of messages / services / actions on the TurtleBot 4 node and makes a much cleaner interface, just a single message. There is the drawback that we don't get any debouncing /  state tracking when using actions, but I think the simplicity is worth it. 

Here is what I propose we do:

* Add a single message on the HRI with four student program slots. 
* Add an event handler to convert the button presses to a publishing a new message (and only on button presses. 
* Remove all the residual code. 
* Add a listener for the new message in the lessons repository. 
* Dispatch the student programs when the button state changes on the message. The student programs can be dispatched via service / action / parameter / message. 

Sorry this wasn't clear.

**Comment by roni-kreinin** [comment]
@kscottz Are you referring to the HMI buttons or the Create 3 buttons?

**Comment by sumedhreddy90** [comment]
As discussed with @kscottz  closing this PR as we will come back with another PR which is simple.

**Pull request closed without merging**
